/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplo;

import static ejemplo.Memory.loadFile;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Freddy
 */
public class ROMDessign extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ROMDessign() {
        initComponents();
        Memory mem=new Memory();
        try{
            String [][] matriz=mem.loadFile();
        }catch(URISyntaxException u){
            System.out.println(u);
        }catch(FileNotFoundException f){
            System.out.println(f);
        }catch(IOException i){
            System.out.println(i);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        micro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        pin2 = new javax.swing.JPanel();
        pin2lbl = new javax.swing.JLabel();
        pin3 = new javax.swing.JPanel();
        pin3lbl = new javax.swing.JLabel();
        pin8 = new javax.swing.JPanel();
        pin8lbl = new javax.swing.JLabel();
        pin1 = new javax.swing.JPanel();
        pin1lbl = new javax.swing.JLabel();
        pin6 = new javax.swing.JPanel();
        pin6lbl = new javax.swing.JLabel();
        pin7 = new javax.swing.JPanel();
        pin7lbl = new javax.swing.JLabel();
        pin5 = new javax.swing.JPanel();
        pin5lbl = new javax.swing.JLabel();
        pin4 = new javax.swing.JPanel();
        pin4lbl = new javax.swing.JLabel();
        pin_oe = new javax.swing.JPanel();
        pin_oe_lbl = new javax.swing.JLabel();
        pin_ce = new javax.swing.JPanel();
        pin_ce_lbl = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        loadFile = new javax.swing.JButton();
        pnlDer = new javax.swing.JPanel();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        pnlSal12 = new javax.swing.JPanel();
        pnlSal13 = new javax.swing.JPanel();
        pnlSal14 = new javax.swing.JPanel();
        pnlSal15 = new javax.swing.JPanel();
        pnlSal16 = new javax.swing.JPanel();
        pnlSal17 = new javax.swing.JPanel();
        pnlSal18 = new javax.swing.JPanel();
        pnlSal11 = new javax.swing.JPanel();
        pnlIzq = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator46 = new javax.swing.JSeparator();
        jSeparator47 = new javax.swing.JSeparator();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator35 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jSeparator50 = new javax.swing.JSeparator();
        jSeparator51 = new javax.swing.JSeparator();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        pnl12 = new javax.swing.JPanel();
        pnl22 = new javax.swing.JPanel();
        pnl31 = new javax.swing.JPanel();
        pnl41 = new javax.swing.JPanel();
        pnl51 = new javax.swing.JPanel();
        pnl61 = new javax.swing.JPanel();
        pnl71 = new javax.swing.JPanel();
        pnl81 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        pnlOE = new javax.swing.JPanel();
        pinProg = new javax.swing.JPanel();
        pinAli = new javax.swing.JPanel();
        pnlCE = new javax.swing.JPanel();
        pnlCE1 = new javax.swing.JPanel();
        pnlOE1 = new javax.swing.JPanel();
        pnl11 = new javax.swing.JPanel();
        pnl21 = new javax.swing.JPanel();
        pnl32 = new javax.swing.JPanel();
        pnl42 = new javax.swing.JPanel();
        pnl82 = new javax.swing.JPanel();
        pnl52 = new javax.swing.JPanel();
        pnl62 = new javax.swing.JPanel();
        pnl72 = new javax.swing.JPanel();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        micro.setBackground(new java.awt.Color(255, 204, 51));
        micro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("A0");
        micro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("A1");
        micro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("A2");
        micro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("A3");
        micro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("A4");
        micro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("A5");
        micro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("A6");
        micro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("A7");
        micro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("A8");
        micro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("A9");
        micro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setText("A10");
        micro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setText("A11");
        micro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setText("A12");
        micro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel15.setText("~CE");
        micro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel16.setText("~OE");
        micro.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel17.setText("~PGM");
        micro.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setText("VPP");
        micro.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel19.setText("D3");
        micro.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setText("D2");
        micro.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setText("D1");
        micro.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel22.setText("D0");
        micro.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel23.setText("D4");
        micro.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel24.setText("D5");
        micro.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel25.setText("D6");
        micro.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel26.setText("D7");
        micro.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel27.setText("Chip de Programación (Físico)");
        micro.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel28.setText("Alimentación");
        micro.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel39.setText("Habilitacion Chip");
        micro.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel40.setText("Habilitacion Chip");
        micro.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel29.setText("SALIDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel29)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel29)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        micro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 50));

        getContentPane().add(micro, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 25, 310, 640));

        pin2.setBackground(new java.awt.Color(51, 51, 255));
        pin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin2MouseClicked(evt);
            }
        });

        pin2lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin2lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin2lbl.setText("0");

        javax.swing.GroupLayout pin2Layout = new javax.swing.GroupLayout(pin2);
        pin2.setLayout(pin2Layout);
        pin2Layout.setHorizontalGroup(
            pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin2Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin2lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin2Layout.setVerticalGroup(
            pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin2lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 82, -1, -1));

        pin3.setBackground(new java.awt.Color(51, 51, 255));
        pin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin3MouseClicked(evt);
            }
        });

        pin3lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin3lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin3lbl.setText("0");

        javax.swing.GroupLayout pin3Layout = new javax.swing.GroupLayout(pin3);
        pin3.setLayout(pin3Layout);
        pin3Layout.setHorizontalGroup(
            pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin3Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin3lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin3Layout.setVerticalGroup(
            pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin3lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 138, -1, -1));

        pin8.setBackground(new java.awt.Color(51, 51, 255));
        pin8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin8MouseClicked(evt);
            }
        });

        pin8lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin8lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin8lbl.setText("0");

        javax.swing.GroupLayout pin8Layout = new javax.swing.GroupLayout(pin8);
        pin8.setLayout(pin8Layout);
        pin8Layout.setHorizontalGroup(
            pin8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin8Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin8lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin8Layout.setVerticalGroup(
            pin8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin8lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 418, -1, -1));

        pin1.setBackground(new java.awt.Color(51, 51, 255));
        pin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin1MouseClicked(evt);
            }
        });

        pin1lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin1lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin1lbl.setText("0");

        javax.swing.GroupLayout pin1Layout = new javax.swing.GroupLayout(pin1);
        pin1.setLayout(pin1Layout);
        pin1Layout.setHorizontalGroup(
            pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin1Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin1lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin1Layout.setVerticalGroup(
            pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin1lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 25, 100, -1));

        pin6.setBackground(new java.awt.Color(51, 51, 255));
        pin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin6MouseClicked(evt);
            }
        });

        pin6lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin6lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin6lbl.setText("0");

        javax.swing.GroupLayout pin6Layout = new javax.swing.GroupLayout(pin6);
        pin6.setLayout(pin6Layout);
        pin6Layout.setHorizontalGroup(
            pin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin6Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin6lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin6Layout.setVerticalGroup(
            pin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin6lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 306, -1, -1));

        pin7.setBackground(new java.awt.Color(51, 51, 255));
        pin7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin7MouseClicked(evt);
            }
        });

        pin7lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin7lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin7lbl.setText("0");

        javax.swing.GroupLayout pin7Layout = new javax.swing.GroupLayout(pin7);
        pin7.setLayout(pin7Layout);
        pin7Layout.setHorizontalGroup(
            pin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin7Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin7lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin7Layout.setVerticalGroup(
            pin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin7lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 362, -1, -1));

        pin5.setBackground(new java.awt.Color(51, 51, 255));
        pin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin5MouseClicked(evt);
            }
        });

        pin5lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin5lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin5lbl.setText("0");

        javax.swing.GroupLayout pin5Layout = new javax.swing.GroupLayout(pin5);
        pin5.setLayout(pin5Layout);
        pin5Layout.setHorizontalGroup(
            pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin5Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin5lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin5Layout.setVerticalGroup(
            pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin5lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 250, -1, -1));

        pin4.setBackground(new java.awt.Color(51, 51, 255));
        pin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pin4MouseClicked(evt);
            }
        });

        pin4lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin4lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin4lbl.setText("0");

        javax.swing.GroupLayout pin4Layout = new javax.swing.GroupLayout(pin4);
        pin4.setLayout(pin4Layout);
        pin4Layout.setHorizontalGroup(
            pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin4Layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(pin4lbl)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );
        pin4Layout.setVerticalGroup(
            pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin4lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 194, -1, -1));

        pin_oe.setBackground(new java.awt.Color(51, 51, 255));

        pin_oe_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin_oe_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin_oe_lbl.setText("0");

        javax.swing.GroupLayout pin_oeLayout = new javax.swing.GroupLayout(pin_oe);
        pin_oe.setLayout(pin_oeLayout);
        pin_oeLayout.setHorizontalGroup(
            pin_oeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(pin_oeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin_oeLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(pin_oe_lbl)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        pin_oeLayout.setVerticalGroup(
            pin_oeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pin_oeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin_oeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin_oe_lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin_oe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 60, 40));

        pin_ce.setBackground(new java.awt.Color(51, 51, 255));

        pin_ce_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pin_ce_lbl.setForeground(new java.awt.Color(255, 255, 255));
        pin_ce_lbl.setText("0");

        javax.swing.GroupLayout pin_ceLayout = new javax.swing.GroupLayout(pin_ce);
        pin_ce.setLayout(pin_ceLayout);
        pin_ceLayout.setHorizontalGroup(
            pin_ceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(pin_ceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin_ceLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(pin_ce_lbl)
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        pin_ceLayout.setVerticalGroup(
            pin_ceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pin_ceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pin_ceLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pin_ce_lbl)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(pin_ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 60, 40));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadFile.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loadFile.setText("Cargar Archivo");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        jPanel14.add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 60));

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 140, 680));

        pnlDer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator29.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 50, 10));

        jSeparator55.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 50, 10));

        jSeparator56.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 50, 20));

        jSeparator57.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 10));

        jSeparator58.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, 10));

        jSeparator59.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 50, 10));

        jSeparator60.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 10));

        jSeparator61.setForeground(new java.awt.Color(0, 51, 0));
        pnlDer.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 50, 10));

        jLabel30.setText("11");
        jLabel30.setToolTipText("");
        pnlDer.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel31.setText("12");
        jLabel31.setToolTipText("");
        pnlDer.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel32.setText("13");
        jLabel32.setToolTipText("");
        pnlDer.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel34.setText("14");
        jLabel34.setToolTipText("");
        pnlDer.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 40, 50));

        jLabel35.setText("15");
        jLabel35.setToolTipText("");
        pnlDer.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 50));

        jLabel37.setText("16");
        jLabel37.setToolTipText("");
        pnlDer.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 40, 50));

        jLabel38.setText("17");
        jLabel38.setToolTipText("");
        pnlDer.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 40, 50));

        jLabel41.setText("18");
        jLabel41.setToolTipText("");
        pnlDer.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 40, 50));

        pnlSal12.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal12Layout = new javax.swing.GroupLayout(pnlSal12);
        pnlSal12.setLayout(pnlSal12Layout);
        pnlSal12Layout.setHorizontalGroup(
            pnlSal12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal12Layout.setVerticalGroup(
            pnlSal12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pnlSal13.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal13Layout = new javax.swing.GroupLayout(pnlSal13);
        pnlSal13.setLayout(pnlSal13Layout);
        pnlSal13Layout.setHorizontalGroup(
            pnlSal13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal13Layout.setVerticalGroup(
            pnlSal13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        pnlSal14.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal14Layout = new javax.swing.GroupLayout(pnlSal14);
        pnlSal14.setLayout(pnlSal14Layout);
        pnlSal14Layout.setHorizontalGroup(
            pnlSal14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal14Layout.setVerticalGroup(
            pnlSal14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        pnlSal15.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal15Layout = new javax.swing.GroupLayout(pnlSal15);
        pnlSal15.setLayout(pnlSal15Layout);
        pnlSal15Layout.setHorizontalGroup(
            pnlSal15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal15Layout.setVerticalGroup(
            pnlSal15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pnlSal16.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal16Layout = new javax.swing.GroupLayout(pnlSal16);
        pnlSal16.setLayout(pnlSal16Layout);
        pnlSal16Layout.setHorizontalGroup(
            pnlSal16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal16Layout.setVerticalGroup(
            pnlSal16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        pnlSal17.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal17Layout = new javax.swing.GroupLayout(pnlSal17);
        pnlSal17.setLayout(pnlSal17Layout);
        pnlSal17Layout.setHorizontalGroup(
            pnlSal17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal17Layout.setVerticalGroup(
            pnlSal17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        pnlSal18.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal18Layout = new javax.swing.GroupLayout(pnlSal18);
        pnlSal18.setLayout(pnlSal18Layout);
        pnlSal18Layout.setHorizontalGroup(
            pnlSal18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal18Layout.setVerticalGroup(
            pnlSal18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        pnlSal11.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlSal11Layout = new javax.swing.GroupLayout(pnlSal11);
        pnlSal11.setLayout(pnlSal11Layout);
        pnlSal11Layout.setHorizontalGroup(
            pnlSal11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSal11Layout.setVerticalGroup(
            pnlSal11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlDer.add(pnlSal11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(pnlDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 60, 250));

        pnlIzq.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 150, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator2);
        jSeparator2.setBounds(50, 570, 10, 30);

        jSeparator3.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator3);
        jSeparator3.setBounds(80, 190, 70, 20);

        jSeparator4.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator4);
        jSeparator4.setBounds(0, 140, 30, 10);

        jSeparator5.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator5);
        jSeparator5.setBounds(0, 200, 40, 10);

        jSeparator6.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator6);
        jSeparator6.setBounds(0, 250, 50, 10);

        jSeparator7.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator7);
        jSeparator7.setBounds(0, 310, 60, 10);

        jSeparator8.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator8);
        jSeparator8.setBounds(0, 370, 70, 10);

        jSeparator9.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator9);
        jSeparator9.setBounds(50, 470, 20, 30);

        jSeparator10.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator10);
        jSeparator10.setBounds(0, 550, 140, 10);

        jSeparator11.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator11);
        jSeparator11.setBounds(0, 600, 50, 30);

        jSeparator12.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator12);
        jSeparator12.setBounds(80, 610, 60, 10);

        jSeparator13.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator13);
        jSeparator13.setBounds(0, 90, 20, 10);

        jSeparator14.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator14);
        jSeparator14.setBounds(20, 50, 70, 40);

        jSeparator15.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator15);
        jSeparator15.setBounds(20, 50, 130, 10);

        jSeparator16.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator16);
        jSeparator16.setBounds(30, 80, 20, 60);

        jSeparator17.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator17);
        jSeparator17.setBounds(30, 80, 120, 10);

        jSeparator18.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator18.setToolTipText("");
        jSeparator18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator18);
        jSeparator18.setBounds(40, 100, 20, 100);

        jSeparator19.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator19);
        jSeparator19.setBounds(40, 100, 110, 10);

        jSeparator20.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator20);
        jSeparator20.setBounds(50, 120, 40, 130);

        jSeparator21.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator21);
        jSeparator21.setBounds(50, 120, 100, 20);

        jSeparator22.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator22);
        jSeparator22.setBounds(60, 150, 20, 160);

        jSeparator23.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator23);
        jSeparator23.setBounds(60, 150, 90, 10);

        jSeparator24.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator24);
        jSeparator24.setBounds(70, 170, 10, 200);

        jSeparator25.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator25);
        jSeparator25.setBounds(70, 170, 80, 10);

        jSeparator26.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator26);
        jSeparator26.setBounds(80, 190, 10, 230);

        jSeparator27.setForeground(new java.awt.Color(0, 51, 0));
        pnlIzq.add(jSeparator27);
        jSeparator27.setBounds(130, 310, 20, 10);

        jSeparator28.setForeground(new java.awt.Color(0, 51, 0));
        pnlIzq.add(jSeparator28);
        jSeparator28.setBounds(90, 220, 60, 10);

        jSeparator30.setForeground(new java.awt.Color(0, 51, 0));
        pnlIzq.add(jSeparator30);
        jSeparator30.setBounds(110, 260, 40, 10);

        jSeparator31.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator31.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlIzq.add(jSeparator31);
        jSeparator31.setBounds(120, 280, 10, 190);

        jSeparator32.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator32.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlIzq.add(jSeparator32);
        jSeparator32.setBounds(110, 260, 10, 210);

        jSeparator33.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlIzq.add(jSeparator33);
        jSeparator33.setBounds(90, 220, 10, 250);

        jSeparator34.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator34.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlIzq.add(jSeparator34);
        jSeparator34.setBounds(100, 240, 10, 230);

        jSeparator36.setForeground(new java.awt.Color(0, 51, 0));
        pnlIzq.add(jSeparator36);
        jSeparator36.setBounds(120, 280, 30, 10);

        jSeparator37.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator37.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pnlIzq.add(jSeparator37);
        jSeparator37.setBounds(130, 310, 20, 160);

        jSeparator38.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator38);
        jSeparator38.setBounds(50, 570, 90, 10);

        jSeparator39.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator39);
        jSeparator39.setBounds(70, 590, 70, 10);

        jSeparator42.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator42);
        jSeparator42.setBounds(80, 610, 10, 30);

        jSeparator43.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator43.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator43);
        jSeparator43.setBounds(80, 610, 10, 30);

        jSeparator44.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator44.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator44);
        jSeparator44.setBounds(80, 610, 10, 30);

        jSeparator46.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator46);
        jSeparator46.setBounds(0, 640, 80, 10);

        jSeparator47.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator47);
        jSeparator47.setBounds(0, 630, 70, 10);

        jSeparator48.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator48.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator48);
        jSeparator48.setBounds(70, 590, 10, 40);

        jSeparator35.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator35);
        jSeparator35.setBounds(0, 420, 80, 10);

        jSeparator49.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator49);
        jSeparator49.setBounds(50, 470, 80, 10);

        jSeparator50.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator50);
        jSeparator50.setBounds(30, 500, 40, 10);

        jSeparator51.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator51);
        jSeparator51.setBounds(40, 520, 20, 10);

        jSeparator52.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator52);
        jSeparator52.setBounds(40, 510, 10, 10);

        jSeparator53.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlIzq.add(jSeparator53);
        jSeparator53.setBounds(40, 510, 20, 10);

        jSeparator54.setForeground(new java.awt.Color(0, 51, 0));
        pnlIzq.add(jSeparator54);
        jSeparator54.setBounds(100, 240, 50, 10);

        jLabel33.setText("1");
        jLabel33.setToolTipText("");
        pnlIzq.add(jLabel33);
        jLabel33.setBounds(130, 580, 40, 50);

        jLabel42.setText("10");
        jLabel42.setToolTipText("");
        pnlIzq.add(jLabel42);
        jLabel42.setBounds(130, 0, 40, 50);

        jLabel43.setText("9");
        jLabel43.setToolTipText("");
        pnlIzq.add(jLabel43);
        jLabel43.setBounds(130, 20, 40, 50);

        jLabel44.setText("8");
        jLabel44.setToolTipText("");
        pnlIzq.add(jLabel44);
        jLabel44.setBounds(130, 50, 40, 50);

        jLabel45.setText("7");
        jLabel45.setToolTipText("");
        pnlIzq.add(jLabel45);
        jLabel45.setBounds(130, 70, 40, 50);

        jLabel46.setText("6");
        jLabel46.setToolTipText("");
        pnlIzq.add(jLabel46);
        jLabel46.setBounds(130, 90, 40, 50);

        jLabel47.setText("5");
        jLabel47.setToolTipText("");
        pnlIzq.add(jLabel47);
        jLabel47.setBounds(130, 120, 40, 50);

        jLabel48.setText("3");
        jLabel48.setToolTipText("");
        pnlIzq.add(jLabel48);
        jLabel48.setBounds(130, 160, 40, 50);

        jLabel49.setText("4");
        jLabel49.setToolTipText("");
        pnlIzq.add(jLabel49);
        jLabel49.setBounds(130, 140, 40, 50);

        jLabel50.setText("25");
        jLabel50.setToolTipText("");
        pnlIzq.add(jLabel50);
        jLabel50.setBounds(130, 190, 40, 50);

        jLabel51.setText("24");
        jLabel51.setToolTipText("");
        pnlIzq.add(jLabel51);
        jLabel51.setBounds(130, 210, 40, 50);

        jLabel52.setText("21");
        jLabel52.setToolTipText("");
        pnlIzq.add(jLabel52);
        jLabel52.setBounds(130, 230, 40, 50);

        jLabel53.setText("23");
        jLabel53.setToolTipText("");
        pnlIzq.add(jLabel53);
        jLabel53.setBounds(130, 250, 40, 50);

        jLabel54.setText("2");
        jLabel54.setToolTipText("");
        pnlIzq.add(jLabel54);
        jLabel54.setBounds(140, 280, 20, 50);

        jLabel55.setText("20");
        jLabel55.setToolTipText("");
        pnlIzq.add(jLabel55);
        jLabel55.setBounds(130, 520, 40, 50);

        jLabel56.setText("22");
        jLabel56.setToolTipText("");
        pnlIzq.add(jLabel56);
        jLabel56.setBounds(130, 540, 40, 50);

        jLabel57.setText("27");
        jLabel57.setToolTipText("");
        pnlIzq.add(jLabel57);
        jLabel57.setBounds(130, 560, 40, 50);

        pnl12.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl12Layout = new javax.swing.GroupLayout(pnl12);
        pnl12.setLayout(pnl12Layout);
        pnl12Layout.setHorizontalGroup(
            pnl12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl12Layout.setVerticalGroup(
            pnl12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl12);
        pnl12.setBounds(0, 20, 10, 10);

        pnl22.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl22Layout = new javax.swing.GroupLayout(pnl22);
        pnl22.setLayout(pnl22Layout);
        pnl22Layout.setHorizontalGroup(
            pnl22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl22Layout.setVerticalGroup(
            pnl22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl22);
        pnl22.setBounds(0, 80, 10, 10);

        pnl31.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl31Layout = new javax.swing.GroupLayout(pnl31);
        pnl31.setLayout(pnl31Layout);
        pnl31Layout.setHorizontalGroup(
            pnl31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl31Layout.setVerticalGroup(
            pnl31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl31);
        pnl31.setBounds(110, 70, 10, 10);

        pnl41.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl41Layout = new javax.swing.GroupLayout(pnl41);
        pnl41.setLayout(pnl41Layout);
        pnl41Layout.setHorizontalGroup(
            pnl41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl41Layout.setVerticalGroup(
            pnl41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl41);
        pnl41.setBounds(110, 90, 10, 10);

        pnl51.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl51Layout = new javax.swing.GroupLayout(pnl51);
        pnl51.setLayout(pnl51Layout);
        pnl51Layout.setHorizontalGroup(
            pnl51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl51Layout.setVerticalGroup(
            pnl51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl51);
        pnl51.setBounds(110, 110, 10, 10);

        pnl61.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl61Layout = new javax.swing.GroupLayout(pnl61);
        pnl61.setLayout(pnl61Layout);
        pnl61Layout.setHorizontalGroup(
            pnl61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl61Layout.setVerticalGroup(
            pnl61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl61);
        pnl61.setBounds(110, 140, 10, 10);

        pnl71.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl71Layout = new javax.swing.GroupLayout(pnl71);
        pnl71.setLayout(pnl71Layout);
        pnl71Layout.setHorizontalGroup(
            pnl71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl71Layout.setVerticalGroup(
            pnl71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl71);
        pnl71.setBounds(110, 160, 10, 10);

        pnl81.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl81Layout = new javax.swing.GroupLayout(pnl81);
        pnl81.setLayout(pnl81Layout);
        pnl81Layout.setHorizontalGroup(
            pnl81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl81Layout.setVerticalGroup(
            pnl81Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl81);
        pnl81.setBounds(110, 180, 10, 10);

        jPanel10.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(jPanel10);
        jPanel10.setBounds(110, 210, 10, 10);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(jPanel2);
        jPanel2.setBounds(110, 230, 10, 10);

        jPanel11.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(jPanel11);
        jPanel11.setBounds(110, 250, 10, 10);

        jPanel12.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(jPanel12);
        jPanel12.setBounds(120, 270, 10, 10);

        jPanel13.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(jPanel13);
        jPanel13.setBounds(130, 300, 10, 10);

        pnlOE.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlOELayout = new javax.swing.GroupLayout(pnlOE);
        pnlOE.setLayout(pnlOELayout);
        pnlOELayout.setHorizontalGroup(
            pnlOELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlOELayout.setVerticalGroup(
            pnlOELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnlOE);
        pnlOE.setBounds(120, 560, 10, 10);

        pinProg.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pinProgLayout = new javax.swing.GroupLayout(pinProg);
        pinProg.setLayout(pinProgLayout);
        pinProgLayout.setHorizontalGroup(
            pinProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pinProgLayout.setVerticalGroup(
            pinProgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pinProg);
        pinProg.setBounds(120, 580, 10, 10);

        pinAli.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pinAliLayout = new javax.swing.GroupLayout(pinAli);
        pinAli.setLayout(pinAliLayout);
        pinAliLayout.setHorizontalGroup(
            pinAliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pinAliLayout.setVerticalGroup(
            pinAliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pinAli);
        pinAli.setBounds(120, 600, 10, 10);

        pnlCE.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlCELayout = new javax.swing.GroupLayout(pnlCE);
        pnlCE.setLayout(pnlCELayout);
        pnlCELayout.setHorizontalGroup(
            pnlCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlCELayout.setVerticalGroup(
            pnlCELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnlCE);
        pnlCE.setBounds(120, 540, 10, 10);

        pnlCE1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlCE1Layout = new javax.swing.GroupLayout(pnlCE1);
        pnlCE1.setLayout(pnlCE1Layout);
        pnlCE1Layout.setHorizontalGroup(
            pnlCE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlCE1Layout.setVerticalGroup(
            pnlCE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnlCE1);
        pnlCE1.setBounds(0, 540, 10, 10);

        pnlOE1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnlOE1Layout = new javax.swing.GroupLayout(pnlOE1);
        pnlOE1.setLayout(pnlOE1Layout);
        pnlOE1Layout.setHorizontalGroup(
            pnlOE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlOE1Layout.setVerticalGroup(
            pnlOE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnlOE1);
        pnlOE1.setBounds(0, 590, 10, 10);

        pnl11.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl11Layout = new javax.swing.GroupLayout(pnl11);
        pnl11.setLayout(pnl11Layout);
        pnl11Layout.setHorizontalGroup(
            pnl11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl11Layout.setVerticalGroup(
            pnl11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl11);
        pnl11.setBounds(110, 20, 10, 10);

        pnl21.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl21Layout = new javax.swing.GroupLayout(pnl21);
        pnl21.setLayout(pnl21Layout);
        pnl21Layout.setHorizontalGroup(
            pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl21Layout.setVerticalGroup(
            pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl21);
        pnl21.setBounds(110, 40, 10, 10);

        pnl32.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl32Layout = new javax.swing.GroupLayout(pnl32);
        pnl32.setLayout(pnl32Layout);
        pnl32Layout.setHorizontalGroup(
            pnl32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl32Layout.setVerticalGroup(
            pnl32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl32);
        pnl32.setBounds(0, 130, 10, 10);

        pnl42.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl42Layout = new javax.swing.GroupLayout(pnl42);
        pnl42.setLayout(pnl42Layout);
        pnl42Layout.setHorizontalGroup(
            pnl42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl42Layout.setVerticalGroup(
            pnl42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl42);
        pnl42.setBounds(0, 190, 10, 10);

        pnl82.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl82Layout = new javax.swing.GroupLayout(pnl82);
        pnl82.setLayout(pnl82Layout);
        pnl82Layout.setHorizontalGroup(
            pnl82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl82Layout.setVerticalGroup(
            pnl82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl82);
        pnl82.setBounds(0, 410, 10, 10);

        pnl52.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl52Layout = new javax.swing.GroupLayout(pnl52);
        pnl52.setLayout(pnl52Layout);
        pnl52Layout.setHorizontalGroup(
            pnl52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl52Layout.setVerticalGroup(
            pnl52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl52);
        pnl52.setBounds(0, 240, 10, 10);

        pnl62.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl62Layout = new javax.swing.GroupLayout(pnl62);
        pnl62.setLayout(pnl62Layout);
        pnl62Layout.setHorizontalGroup(
            pnl62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl62Layout.setVerticalGroup(
            pnl62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl62);
        pnl62.setBounds(0, 300, 10, 10);

        pnl72.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnl72Layout = new javax.swing.GroupLayout(pnl72);
        pnl72.setLayout(pnl72Layout);
        pnl72Layout.setHorizontalGroup(
            pnl72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnl72Layout.setVerticalGroup(
            pnl72Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlIzq.add(pnl72);
        pnl72.setBounds(0, 360, 10, 10);

        getContentPane().add(pnlIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 650));

        jSeparator40.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 120, 10));

        jSeparator45.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 120, -1));

        jSeparator41.setForeground(new java.awt.Color(0, 51, 0));
        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 10, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setText("Alimentación");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        Memory prog = new Memory();
        // Programa programa= new Programa();
        try {
            String[][] matriz = prog.loadFile();

        } catch (URISyntaxException o) {
            System.out.println("Error");
        } catch (FileNotFoundException f) {
            System.out.println("Error");
        } catch (IOException i) {
            System.out.println("Error");
        }

    }//GEN-LAST:event_loadFileActionPerformed

    private void pin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin1MouseClicked
        if (pin1lbl.getText().toString() == "0") {
            pin1lbl.setText("1");
            pin1.setBackground(Color.red);
            pnl11.setBackground(Color.red);
            pnl12.setBackground(Color.red);
        } else {
            pin1lbl.setText("0");
            pin1.setBackground(Color.BLUE);
            pnl11.setBackground(Color.BLUE);
            pnl12.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin1MouseClicked

    private void pin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin2MouseClicked
        if (pin2lbl.getText().toString() == "0") {
            pin2lbl.setText("1");
            pin2.setBackground(Color.red);
            pnl21.setBackground(Color.red);
            pnl22.setBackground(Color.red);
        } else {
            pin2lbl.setText("0");
            pin2.setBackground(Color.BLUE);      
            pnl21.setBackground(Color.BLUE);
            pnl22.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin2MouseClicked

    private void pin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin3MouseClicked
        if (pin3lbl.getText().toString() == "0") {
            pin3lbl.setText("1");
            pin3.setBackground(Color.red);
            pnl31.setBackground(Color.red);
            pnl32.setBackground(Color.red);
        } else {
            pin3lbl.setText("0");
            pin3.setBackground(Color.BLUE);
            pnl31.setBackground(Color.BLUE);
            pnl32.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin3MouseClicked

    private void pin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin4MouseClicked
        if (pin4lbl.getText().toString() == "0") {
            pin4lbl.setText("1");
            pin4.setBackground(Color.red);
            pnl41.setBackground(Color.red);
            pnl42.setBackground(Color.red);
        } else {
            pin4lbl.setText("0");
            pin4.setBackground(Color.BLUE);
            pnl41.setBackground(Color.BLUE);
            pnl42.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin4MouseClicked

    private void pin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin5MouseClicked
        if (pin5lbl.getText().toString() == "0") {
            pin5lbl.setText("1");
            pin5.setBackground(Color.red);
            pnl51.setBackground(Color.red);
            pnl52.setBackground(Color.red);
        } else {
            pin5lbl.setText("0");
            pin5.setBackground(Color.BLUE);
            pnl51.setBackground(Color.BLUE);
            pnl52.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin5MouseClicked

    private void pin7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin7MouseClicked
        if (pin7lbl.getText().toString() == "0") {
            pin7lbl.setText("1");
            pin7.setBackground(Color.red);
            pnl71.setBackground(Color.red);
            pnl72.setBackground(Color.red);
        } else {
            pin7lbl.setText("0");
            pin7.setBackground(Color.BLUE);
            pnl71.setBackground(Color.BLUE);
            pnl72.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin7MouseClicked

    private void pin8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin8MouseClicked
        if (pin8lbl.getText().toString() == "0") {
            pin8lbl.setText("1");
            pin8.setBackground(Color.red);
            pnl81.setBackground(Color.red);
            pnl82.setBackground(Color.red);
        } else {
            pin8lbl.setText("0");
            pin8.setBackground(Color.BLUE);
            pnl81.setBackground(Color.BLUE);
            pnl82.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin8MouseClicked

    private void pin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pin6MouseClicked
        if (pin6lbl.getText().toString() == "0") {
            pin6lbl.setText("1");
            pin6.setBackground(Color.red);
            pnl61.setBackground(Color.red);
            pnl62.setBackground(Color.red);
        } else {
            pin6lbl.setText("0");
            pin6.setBackground(Color.BLUE);
            pnl61.setBackground(Color.BLUE);
            pnl62.setBackground(Color.BLUE);
        }
    }//GEN-LAST:event_pin6MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        String posicion = pin1lbl.getText()+""+pin2lbl.getText()+""+pin3lbl.getText()+""+pin4lbl.getText()+""+pin5lbl.getText()+""+pin6lbl.getText()+""+pin7lbl.getText()+""+pin8lbl.getText();
        int pos=Integer.parseInt(posicion,2);  
        /*for (int i = 0; i < matriz.length; i++) {
            
        }*/
        System.out.println(posicion+"-"+pos);
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROMDessign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROMDessign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROMDessign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROMDessign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROMDessign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton loadFile;
    private javax.swing.JPanel micro;
    private javax.swing.JPanel pin1;
    private javax.swing.JLabel pin1lbl;
    private javax.swing.JPanel pin2;
    private javax.swing.JLabel pin2lbl;
    private javax.swing.JPanel pin3;
    private javax.swing.JLabel pin3lbl;
    private javax.swing.JPanel pin4;
    private javax.swing.JLabel pin4lbl;
    private javax.swing.JPanel pin5;
    private javax.swing.JLabel pin5lbl;
    private javax.swing.JPanel pin6;
    private javax.swing.JLabel pin6lbl;
    private javax.swing.JPanel pin7;
    private javax.swing.JLabel pin7lbl;
    private javax.swing.JPanel pin8;
    private javax.swing.JLabel pin8lbl;
    private javax.swing.JPanel pinAli;
    private javax.swing.JPanel pinProg;
    private javax.swing.JPanel pin_ce;
    private javax.swing.JLabel pin_ce_lbl;
    private javax.swing.JPanel pin_oe;
    private javax.swing.JLabel pin_oe_lbl;
    private javax.swing.JPanel pnl11;
    private javax.swing.JPanel pnl12;
    private javax.swing.JPanel pnl21;
    private javax.swing.JPanel pnl22;
    private javax.swing.JPanel pnl31;
    private javax.swing.JPanel pnl32;
    private javax.swing.JPanel pnl41;
    private javax.swing.JPanel pnl42;
    private javax.swing.JPanel pnl51;
    private javax.swing.JPanel pnl52;
    private javax.swing.JPanel pnl61;
    private javax.swing.JPanel pnl62;
    private javax.swing.JPanel pnl71;
    private javax.swing.JPanel pnl72;
    private javax.swing.JPanel pnl81;
    private javax.swing.JPanel pnl82;
    private javax.swing.JPanel pnlCE;
    private javax.swing.JPanel pnlCE1;
    private javax.swing.JPanel pnlDer;
    private javax.swing.JPanel pnlIzq;
    private javax.swing.JPanel pnlOE;
    private javax.swing.JPanel pnlOE1;
    private javax.swing.JPanel pnlSal11;
    private javax.swing.JPanel pnlSal12;
    private javax.swing.JPanel pnlSal13;
    private javax.swing.JPanel pnlSal14;
    private javax.swing.JPanel pnlSal15;
    private javax.swing.JPanel pnlSal16;
    private javax.swing.JPanel pnlSal17;
    private javax.swing.JPanel pnlSal18;
    // End of variables declaration//GEN-END:variables
}
